version: 2
mkdocs:
  configuration: mkdocs.yml
build:
  apt_packages:
    - php
python:
  version: 3.7
  install:
    - method: pip
      path: .
    - requirements: .readthedocs-requirements.txt
formats: all