version: 2
mkdocs:
  configuration: mkdocs.yml
build:
  apt_packages:
    - php8
    - php8-xml
    - php8-mbstring
python:
  version: "3.7"
  install:
    - requirements: readthedocs-reqs.txt
formats: all