version: 2
mkdocs:
  configuration: mkdocs.yml
build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  apt_packages:
    - php8.2
    - php8.2-xml
    - php8.2-mbstring
python:
  install:
    - requirements: readthedocs-reqs.txt
formats: all