version: 2
mkdocs:
  configuration: mkdocs.yml
build:
  apt_packages:
    - php
    - php-xml
    - php-mbstring
python:
  version: "3.7"
  install:
    - requirements: readthedocs-reqs.txt
formats: all